version: '3.3'

services:
  controller:
    build:
      context: ./controller
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc.yaml
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: pass
      CASC_JENKINS_CONFIG: /var/jenkins_conf/
      JENKINS_URL: http://127.0.0.1:8080/
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      # named_volume_name:/container/path
      - jenkins-controller:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  agent:
   image: jenkins/ssh-agent:jdk11
    # privileged: true
    # user: root
    # container_name: agent
   ports:
     - 22:22
   environment:
    - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCl17uFJ7GEzN9uVARaKn1nihxT+JUoScspUTEk83+XENmDtOumUA8Foved2fB4AuYkh7bz6vTolM2UYeDyU3YnM3DPLfJJl5hRM7g5nlgZDAQFBUWk1xHWhvjSdJn75fv2FY1ilhN2gRanhGn9Lp/r90oxxydTM+u7gPtaOTE/AKcc1TTY1b/89hBa2ELFo34u9ctUacpQox3eIMmvIVlTKoFe6Tt2/CEmxEUUYdr/fb0gr57k48tBxn1/gdvbo54j/zBzrXWiJm4LvyyhZMqRhL4WSza+WIx1EPbm5+kuXe5x5G6FOyckxp8QXhKZxjA5e/tSsziD+XkV2wqIHbg1 creatiwww@Marias-MacBook-Pro.local

volumes:
  jenkins-controller:
